Update esp

diff --git a/esp b/esp
--- a/esp
+++ b/esp
@@ -332,7 +332,7 @@ esp_help_sys-info(){
 # -------------------
 
 alias lsip='ifconfig | grep "inet addr"| grep -v "127.0.0.1"';
-alias lsip-real="curl -s http://cpanel.net/showip.cgi";
+alias lsip-real="curl -s http://cpanel.com/showip.shtml";
 alias lsip-mainip="strings /var/cpanel/mainip";
 alias ips=$(ifconfig | awk '/inet/ {if ($2!~/127.0|:$/) print $2}' | awk -F: '{print "echo "$2}');
 
@@ -358,7 +358,7 @@ function esp_fcdns_check() {
        local rdns_ip="`dig @4.2.2.2 +time=1 +short -x $ip_to_check | xargs dig +short `";
    fi
    if [ "$ip_to_check" = "$rdns_ip" ]; then
-       echo "$(tput setaf 3)$ip_to_check$(tput setaf 2) PASSED FCrDNS validation $(tput sgr0)$ip_to_check$(tput setaf 3)->$(tput sgr0)$rdns$(tput setaf 3)->$(tput sgr0)$rdns_ip";
+       echo "$(tput setaf 3)$ip_to_check$(tput setaf 2) PASSED FCrDNS valadation $(tput sgr0)$ip_to_check$(tput setaf 3)->$(tput sgr0)$rdns$(tput setaf 3)->$(tput sgr0)$rdns_ip";
    else
        echo "$(tput setaf 3)$ip_to_check$(tput setaf 1) FAILED FCrDNS validation $(tput sgr0)$ip_to_check$(tput setaf 3)->$(tput sgr0)$rdns$(tput setaf 3)->$(tput sgr0)$rdns_ip";
    fi
@@ -480,49 +480,47 @@ function esp_migrations () {
 };
 
 #
-# VIRTFS TOOLBOX Commands
-# --------------------------
-
-function virtfs_mounts() {
-        local USER=$1;
-        /usr/local/cpanel/3rdparty/bin/perl -MCpanel::Filesys::Virtfs -MData::Dumper -e 'my @blah = Cpanel::Filesys::Virtfs::get_virtfs_mounts(); foreach (@blah) { $_ =~  /((\/\w+)*\/?)/; print $1."\n"; }';
-};
-
-function virtfs_exim_deps() {
-        local USER=$1;
-        /usr/local/cpanel/3rdparty/bin/perl -MCpanel::Filesys::Virtfs -MData::Dumper -e 'my @blah = Cpanel::Filesys::Virtfs::get_exim_deps(); foreach (@blah) { $_ =~  /((\/\w+)*\/?)/; print $1."\n"; }';
-};
-
-function virtfs_mount_points() {
-        local USER=$1;
-        /usr/local/cpanel/3rdparty/bin/perl -MCpanel::Filesys::Virtfs -MData::Dumper -e 'my @blah = Cpanel::Filesys::Virtfs::get_virtfs_mount_points(); foreach (@blah) { $_ =~  /((\/\w+)*\/?)/; print $1."\n"; }'
-};
-
-function virtfs_jailshell_path() {
-        local USER=$1;
-        /usr/local/cpanel/3rdparty/bin/perl -MCpanel::Filesys::Virtfs -MData::Dumper -e 'my @blah = Cpanel::Filesys::Virtfs::get_jailshell_path(); foreach (@blah) { $_ =~  /((\/\w+)*\/?)/; print $1."\n"; }'
-};
-
-function esp_help_virtfs() {
-    help_section "Various utilities for obtaining virtfs information";
-	help_command "virtfs_mounts" "Prints out the currently mounted virtfs mounts.";
-	help_command "virtfs_exim_deps" "Prints out virtfs exim dependencies";
-	help_command "virtfs_mount_points" "Prints out all current virtfs mount points on the server";
-	help_command "virtfs_jailshell_path" "Prints out the current path for jailshell.  This probably won't change much.";
-};
-
-
-#
 # Other and Special Commands
 # --------------------------
+
+
+function rpmdbfix () {
+   local cur_time_stamp="`date +%F.%T`";
+   local backupdir="/root/cptechs/backups/rpmdb-$cur_time_stamp";
+   echo "Backing up old rpm database";
+   mkdir -vp $backupdir;
+   tar zcf $backupdir/rpmdb.tar.gz /var/lib/rpm;
+
+   if [[ $? -ne 0 ]]; then
+       echo "Tarball backup of existing rpm database failed.  Exiting.";
+       exit -1;
+   fi
+
+   mv -v /var/lib/rpm/__db* $backupdir;  
+   if [[ $? -ne 0 ]]; then
+        echo "Failure Moving Aside old Database";
+   fi
+
+   /usr/lib/rpm/rpmdb_verify /var/lib/rpm/Packages
+   if [[ $? -ne 0 ]]; then
+       echo "RPM Package fail, repairing....";
+       mv -v {/usr/lib/rpm/,$backupdir}Packages;
+       /usr/lib/rpm/rpmdb_dump $backupdir/Packages | /usr/lib/rpm/rpmdb_load /var/lib/rpm/Packages;
+      /usr/lib/rpm/rpmdb_verify /var/lib/rpm/Packages;
+   fi
+
+rpm -qa 1> /dev/null
+rpm --rebuilddb;
+}
+
 
 alias ssp="curl -s --insecure https://ssp.cpanel.net/SSP/run | sh ";
 alias check_libkey="sh <(curl -s --insecure https://raw.githubusercontent.com/cPMarco/cpm/master/libkey_check.sh) -v";
 alias wo="/usr/local/cpanel/scripts/whoowns";
 alias ccrpms='/usr/local/cpanel/scripts/check_cpanel_rpms';
 alias perdir='awk '\''BEGIN{dir=DIR?DIR:ENVIRON["PWD"];l=split(dir,parts,"/");last="";for(i=1;i<l+1;i++){d=last"/"parts[i];gsub("//","/",d);system("stat --printf \"%a\t%u\t%g\t\" \""d"\"; echo -n \" \";ls -ld \""d"\"");last=d}}'\'''
-alias csi="esp_script_dl \"csi.pl\" \"http://csi.cptechs.info/csi.pl\"";
-
+alias csi="esp_script_dl \"csi.pl\" \"https://raw.githubusercontent.com/cPanelTechs/CSI/master/csi.pl\"";
+alias hostname-history="grep -A 999 sub_domains /var/cpanel/userdata/nobody/main | grep -v sub_domains| sed 's/\ \ \-\ //g'";
 
 function oddthings () {
     echo  "$(tput bold)odd things$(tput sgr0)";
@@ -539,7 +537,21 @@ function esp_help_other() {
         help_command "wo" "Alias for /scripts/whoowns";
         help_command "ccrpms" "Alias for /scripts/check_cpanel_rpms";
 	help_command "csi" " Runs CSI";
+	help_command "rpmdbfix" "Safly backups and repairs the rpm database";
+	help_command "hostname-history" "Returns all of the hostnames used by the server ";
 }
+
+
+
+
+
+
+
+
+
+
+
+
 
 #
 # Functions to assist with displaying the help section
@@ -568,7 +580,6 @@ function cphelp() {
     esp_help_PHP_Apache;
     esp_help_bash_nav;
     esp_migrations;
-    esp_help_virtfs;
     esp_help_other;
 }
 #
